# 📊 Estudo de Caso: Desempenho de Alunos

Você foi contratado como cientista de dados para analisar o desempenho de uma turma.
Seu objetivo é gerar insights para melhorar o ensino.

Utilizando o material e as métricas apresentadas na aula de hoje, apresente seus _insigths_ para o _dataset_ apresentado:

In [192]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('dataset_estudo_estatistica.csv')
df.head()

,horas_estudo,acessos_plataforma,faltas,tempo_resolucao,bolsa_estagio,turno,linguagem,nota
0,7,39,10,167,1,Manhã,Java,75.596400
1,4,39,9,183,1,Manhã,Java,0.000000
2,8,37,6,166,0,Manhã,C,66.178579
3,5,9,11,109,0,Noite,Python,35.059806
4,7,110,8,166,1,Noite,C,57.371902

In [193]:
df.describe()

,horas_estudo,acessos_plataforma,faltas,tempo_resolucao,bolsa_estagio,nota
count,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000
mean,5.362500,59.950000,5.275000,128.412500,0.512500,44.635219
std,2.615648,33.920197,3.676731,48.334985,0.502997,27.985507
min,1.000000,5.000000,0.000000,21.000000,0.000000,0.000000
25%,3.000000,32.750000,2.000000,99.250000,0.000000,21.701485
50%,5.000000,53.500000,5.000000,138.500000,1.000000,47.506161
75%,8.000000,92.500000,8.000000,167.000000,1.000000,64.595390
max,9.000000,119.000000,11.000000,197.000000,1.000000,100.000000

## Exercício 1
Descreva e analise algo relevante nos dados.

In [194]:
media_horas_estudo = df["horas_estudo"].mean()
mediana_horas_estudo = df["horas_estudo"].median()
moda_horas_estudo = df["horas_estudo"].mode()
desvio_padrao =  df["horas_estudo"].std()
print("Média: ",media_horas_estudo)
print("Mediana: ", mediana_horas_estudo)
print("Moda: ",moda_horas_estudo)
print("Desvio padrão: ",desvio_padrao)
print("""\nANÁLISE\nA média de horas de estudo foi de aproximadamente 5,36 horas, com mediana de 5, indicando uma distribuição relativamente equilibrada dos dados. A moda igual a 8 horas sugere que um número significativo de alunos apresenta alta dedicação aos estudos. O desvio padrão de 2,62 indica uma variabilidade moderada, mostrando que, embora haja diferenças entre os alunos, a maioria se concentra em torno da média.""")

Média:  5.3625
Mediana:  5.0
Moda:  0    8
Name: horas_estudo, dtype: int64
Desvio padrão:  2.615647897567758

ANÁLISE
A média de horas de estudo foi de aproximadamente 5,36 horas, com mediana de 5, indicando uma distribuição relativamente equilibrada dos dados. A moda igual a 8 horas sugere que um número significativo de alunos apresenta alta dedicação aos estudos. O desvio padrão de 2,62 indica uma variabilidade moderada, mostrando que, embora haja diferenças entre os alunos, a maioria se concentra em torno da média.

## Exercício 2
Descreva e analise algo relevante nos dados.

In [195]:
faltas_turno = df.groupby('turno')['faltas']

print("\nMÉDIA\n",faltas_turno.mean())
print("\nMEDIANA\n",faltas_turno.median())
print("\nDESVIO PADRÃO\n",faltas_turno.std())
print("\nVARIÂNCIA\n",faltas_turno.var())
print("\nVALOR MÁXIMO\n",faltas_turno.max())
print("\nVALOR MÍNIMO\n",faltas_turno.min())
print("\nANÁLISE\nAqui é possível concluir que a média de faltas dos alunos que estudam no período da noite é maior que a do turno da manhã, notando que os alunos tendem a faltar mais no curso noturno, porém o desvio padrão é relativamente alto, indicando que há uma grande variabilidade, e que nem todos seguem esse padrão")

MÉDIA
 turno
Manhã    4.6
Noite    5.8
Name: faltas, dtype: float64

MEDIANA
 turno
Manhã    5.0
Noite    6.0
Name: faltas, dtype: float64

DESVIO PADRÃO
 turno
Manhã    3.647723
Noite    3.653143
Name: faltas, dtype: float64

VARIÂNCIA
 turno
Manhã    13.305882
Noite    13.345455
Name: faltas, dtype: float64

VALOR MÁXIMO
 turno
Manhã    10
Noite    11
Name: faltas, dtype: int64

VALOR MÍNIMO
 turno
Manhã    0
Noite    0
Name: faltas, dtype: int64

ANÁLISE
Aqui é possível concluir que a média de faltas dos alunos que estudam no período da noite é maior que a do turno da manhã, notando que os alunos tendem a faltar mais no curso noturno, porém o desvio padrão é relativamente alto, indicando que há uma grande variabilidade, e que nem todos seguem esse padrão

## Exercício 3
Descreva e analise algo relevante nos dados.

In [196]:
correlacao = df[['faltas','nota']].corr()
media_faltas = df['faltas'].mean()
desvio = df['faltas'].std()
print(correlacao, "\nMédia de faltas: ",media_faltas, "\nDesvio: ",desvio, "\nANÁLISE\nAqui podemos notar que a relação entre esses dois atributos não é tão direta, mas que há uma pequena relação entre as faltas e as notas dos alunos, sendo quanto maior a quantidade de faltas, menores as notas. E é possível ver um alto grau de desvio padrão também, o que indica valores discrepantes e variados em relação à média das faltas, que era em torno de 5,275)")

          faltas      nota
faltas  1.000000 -0.196724
nota   -0.196724  1.000000
Média de faltas:  5.275
Desvio:  3.6767314873919936
ANÁLISE
Aqui podemos notar que a relação entre esses dois atributos não é tão direta, mas que há uma pequena relação entre as faltas e as notas dos alunos, sendo quanto maior a quantidade de faltas, menores as notas. E é possível ver um alto grau de desvio padrão também, o que indica valores discrepantes e variados em relação à média das faltas, que era em torno de 5,275)

## Exercício 4
Descreva e analise algo relevante nos dados.

In [197]:
notas_turno = df.groupby('turno')['nota']

print("Médias:\n",notas_turno.mean(),
      "\n\nMedianas:\n",notas_turno.median(),
      "\n\nDesvio:\n",notas_turno.std(),
      "\n\nANÁLISE\nPodemos notar que os alunos do turno da manhã tem média e mediana de notas um pouco maiores, então no geral o pessoal da manhã tem um desempenho um pouco melhor nas notas. Porém, o desvio padrão é bem alto nos dois casos, o que mostra que as notas são bem espalhadas. Então mesmo existindo uma pequena diferença entre os turnos, não podemos dizer que é uma relação muito forte.")

Médias:
 turno
Manhã    47.302129
Noite    42.560956
Name: nota, dtype: float64

Medianas:
 turno
Manhã    47.754345
Noite    43.701437
Name: nota, dtype: float64

Desvio:
 turno
Manhã    29.322575
Noite    27.050330
Name: nota, dtype: float64

ANÁLISE
Podemos notar que os alunos do turno da manhã tem média e mediana de notas um pouco maiores, então no geral o pessoal da manhã tem um desempenho um pouco melhor nas notas. Porém, o desvio padrão é bem alto nos dois casos, o que mostra que as notas são bem espalhadas. Então mesmo existindo uma pequena diferença entre os turnos, não podemos dizer que é uma relação muito forte.

## Exercício 5
Descreva e analise algo relevante nos dados.

In [198]:
horas_bolsa = df.groupby('bolsa_estagio')['horas_estudo']
print(
"\nMédia:\n",horas_bolsa.mean(),
"\n\nMediana:\n",horas_bolsa.median(),
"\n\nDesvio:\n",horas_bolsa.std(), "\n\nANÁLISE\nA partir dessa comparação, podemos concluir que bolsistas não estudam por mais tempo que não bolsistas, possuir bolsa estágio praticamente não interfere na quantidade de horas de estudo dos alunos, ambos se dedicando por tempos parecidos")

Média:
 bolsa_estagio
0    5.205128
1    5.512195
Name: horas_estudo, dtype: float64

Mediana:
 bolsa_estagio
0    5.0
1    5.0
Name: horas_estudo, dtype: float64

Desvio:
 bolsa_estagio
0    2.587210
1    2.665726
Name: horas_estudo, dtype: float64

ANÁLISE
A partir dessa comparação, podemos concluir que bolsistas não estudam por mais tempo que não bolsistas, possuir bolsa estágio praticamente não interfere na quantidade de horas de estudo dos alunos, ambos se dedicando por tempos parecidos

## Exercício 6
Descreva e analise algo relevante nos dados.

In [199]:
notas_linguagem = df.groupby('linguagem')['nota']

print("Quantidade de notas:\n",notas_linguagem.count(),
      "\n\nMédia:",notas_linguagem.mean(),
      "\n\nMediana:\n",notas_linguagem.median(),
      "\n\nDesvio:\n",notas_linguagem.std(),
      "\n\nANÁLISE\nAqui podemos notar que há uma maior quantidade de alunos estudando as linguagens java e python do que C, e podemos ver que apesar de haver um alto desvio padrão nos valores, os alunos tendem a ter notas maiores em C e Python, e um pouco menores em Java")

Quantidade de notas:
 linguagem
C         20
Java      31
Python    29
Name: nota, dtype: int64

Média: linguagem
C         47.281207
Java      40.353170
Python    47.387763
Name: nota, dtype: float64

Mediana:
 linguagem
C         52.145221
Java      37.927791
Python    47.573688
Name: nota, dtype: float64

Desvio:
 linguagem
C         24.527962
Java      31.738182
Python    26.249884
Name: nota, dtype: float64

ANÁLISE
Aqui podemos notar que há uma maior quantidade de alunos estudando as linguagens java e python do que C, e podemos ver que apesar de haver um alto desvio padrão nos valores, os alunos tendem a ter notas maiores em C e Python, e um pouco menores em Java

## Exercício 7
Descreva e analise algo relevante nos dados.

In [200]:
horas_linguagem = df.groupby('linguagem')['horas_estudo']

print("\nMédia:",horas_linguagem.mean(),
"\n\nDesvio:\n",horas_linguagem.std(), "\n\nANÁLISE\nAqui podemos observar que as horas de estudo para as três linguagens em média gira em torno de cinco horas, não apresentando uma maior ou menor demanda de horas para os estudos de uma linguagem específica em comparação com outra")

Média: linguagem
C         5.350000
Java      5.096774
Python    5.655172
Name: horas_estudo, dtype: float64

Desvio:
 linguagem
C         2.476734
Java      2.879292
Python    2.468022
Name: horas_estudo, dtype: float64

ANÁLISE
Aqui podemos observar que as horas de estudo para as três linguagens em média gira em torno de cinco horas, não apresentando uma maior ou menor demanda de horas para os estudos de uma linguagem específica em comparação com outra

## Exercício 8
Descreva e analise algo relevante nos dados.

In [201]:
notas_estudo = df[['nota','horas_estudo']]

print(notas_estudo.corr(), "\n\nANÁLISE\nAqui podemos observar, a partir da correlação entre as notas dos alunos e a quantidade de horas de estudo deles, que existe uma forte relação entre essas variáveis, com os alunos que dedicam mais horas estudando tendo notas maiores, em comparação com os que estudam por menos tempo")

                  nota  horas_estudo
nota          1.000000      0.918086
horas_estudo  0.918086      1.000000

ANÁLISE
Aqui podemos observar, a partir da correlação entre as notas dos alunos e a quantidade de horas de estudo deles, que existe uma forte relação entre essas variáveis, com os alunos que dedicam mais horas estudando tendo notas maiores, em comparação com os que estudam por menos tempo

## Exercício 9
Descreva e analise algo relevante nos dados.

In [202]:
media_estudo = df['horas_estudo'].mean()

alto_estudo = df[df['horas_estudo'] > media_estudo]['nota']
baixo_estudo = df[df['horas_estudo'] <= media_estudo]['nota']
print("Média de notas com alto estudo:\n",alto_estudo.mean(),"\n\nMédia de notas com baixo estudo:\n",baixo_estudo.mean(),"\n\nDesvios padrão:\n",alto_estudo.std(),
baixo_estudo.std(),"\n\nANÁLISE\nAqui podemos comparar a média das notas de quem estuda por mais tempo, com em torno de 67 pontos, e quem estuda por menos tempo, com em torno de 23 pontos, apesar de uma certa variância nesses valores, apontados pelo alto desvio padrão")

Média de notas com alto estudo:
 67.42810685291037

Média de notas com baixo estudo:
 22.954179218392547

Desvios padrão:
 16.47109184964856 17.341236928206808

ANÁLISE
Aqui podemos comparar a média das notas de quem estuda por mais tempo, com em torno de 67 pontos, e quem estuda por menos tempo, com em torno de 23 pontos, apesar de uma certa variância nesses valores, apontados pelo alto desvio padrão

## Exercício 10
Descreva e analise algo relevante nos dados.

In [203]:
notas_bolsa = df.groupby('bolsa_estagio')['nota']

print("Média notas:\n",notas_bolsa.mean(),
      "\n\nMediana notas:\n",notas_bolsa.median(),"\n\nDesvio padrão:\n",
      notas_bolsa.std(),
      "\n\nANÁLISE\nAqui podemos observar que não há significativa interferência nas notas dos alunos o fato de eles possuirem ou não bolsas de estágio, pois possuem uma média e mediana de notas muito próximas, apesar de um alto desvio padrão também, o que mostra que os valores são bem espalhados")

Média notas:
 bolsa_estagio
0    44.654595
1    44.616788
Name: nota, dtype: float64

Mediana notas:
 bolsa_estagio
0    45.665746
1    47.573688
Name: nota, dtype: float64

Desvio padrão:
 bolsa_estagio
0    25.605107
1    30.396651
Name: nota, dtype: float64

ANÁLISE
Aqui podemos observar que não há significativa interferência nas notas dos alunos o fato de eles possuirem ou não bolsas de estágio, pois possuem uma média e mediana de notas muito próximas, apesar de um alto desvio padrão também, o que mostra que os valores são bem espalhados

## Exercício 11
Descreva e analise algo relevante nos dados.

In [204]:
faltas_linguagem = df.groupby('linguagem')['faltas']

print("Quantidade:\n",faltas_linguagem.count(),
      "\n\nMédia:\n",faltas_linguagem.mean(),
      "\n\nMediana:\n",faltas_linguagem.median(),
      "\n\nDesvio padrão:\n",faltas_linguagem.std(),
      "\n\nANÁLISE\nAqui podemos notar que há uma maior quantidade de alunos cursando as linguagens java e python doque a linguagem C, e que a média de faltas dos alunos costuma ser maior nas aulas da linguagem java, seguidas das de python e sendo menores as de C")

Quantidade:
 linguagem
C         20
Java      31
Python    29
Name: faltas, dtype: int64

Média:
 linguagem
C         3.750000
Java      6.225806
Python    5.310345
Name: faltas, dtype: float64

Mediana:
 linguagem
C         3.0
Java      7.0
Python    5.0
Name: faltas, dtype: float64

Desvio padrão:
 linguagem
C         3.522484
Java      3.774561
Python    3.434109
Name: faltas, dtype: float64

ANÁLISE
Aqui podemos notar que há uma maior quantidade de alunos cursando as linguagens java e python doque a linguagem C, e que a média de faltas dos alunos costuma ser maior nas aulas da linguagem java, seguidas das de python e sendo menores as de C

## Exercício 12
Descreva e analise algo relevante nos dados.

In [205]:
tempo_nota = df[['tempo_resolucao','nota']]

print(tempo_nota.corr())
print("\nANÁLISE\nObservando o índice de correlação entre as notas dos alunos e o tempo de resolução das provas, podemos notar que praticamente não há relação entre essas variáveis, não importando o tempo de resolução no resultado das notas dos alunos")

                 tempo_resolucao      nota
tempo_resolucao         1.000000 -0.030751
nota                   -0.030751  1.000000

ANÁLISE
Observando o índice de correlação entre as notas dos alunos e o tempo de resolução das provas, podemos notar que praticamente não há relação entre essas variáveis, não importando o tempo de resolução no resultado das notas dos alunos

## Exercício 13
Descreva e analise algo relevante nos dados.

In [206]:
acessos_nota = df[['acessos_plataforma','nota']]

print(acessos_nota.corr())
print("\nANÁLISE\nA partir desse índice de correlação entre as notas dos alunos e a quantidade de acessos na plataforma, vemos que há uma pequena relação entre esses fatores, mas quase insignificantes, não sendo determinante no resultado das notas a quantidade de vezes que os alunos acessaram a plataforma")

                    acessos_plataforma      nota
acessos_plataforma            1.000000 -0.140078
nota                         -0.140078  1.000000

ANÁLISE
A partir desse índice de correlação entre as notas dos alunos e a quantidade de acessos na plataforma, vemos que há uma pequena relação entre esses fatores, mas quase insignificantes, não sendo determinante no resultado das notas a quantidade de vezes que os alunos acessaram a plataforma

## Exercício 14
Descreva e analise algo relevante nos dados.

In [207]:
acessos_horas = df[['acessos_plataforma','horas_estudo']].corr()
print(acessos_horas)
print("\nANÁLISE\nCom a análise do índice de correlação entre a quantidade de acessos à plataforma e a quantidade de horas de estudo dos alunos, podemos notar que a relação entre essas variáveis é quase nula, com as horas de estudo não interferindo nos acessos à plataforma")

                    acessos_plataforma  horas_estudo
acessos_plataforma            1.000000     -0.095668
horas_estudo                 -0.095668      1.000000

ANÁLISE
Com a análise do índice de correlação entre a quantidade de acessos à plataforma e a quantidade de horas de estudo dos alunos, podemos notar que a relação entre essas variáveis é quase nula, com as horas de estudo não interferindo nos acessos à plataforma

## Exercício 15
Descreva e analise algo relevante nos dados.

In [208]:
resolucao_estudo = df[['tempo_resolucao','horas_estudo']].corr()
print(resolucao_estudo)
print("\nANÁLISE\nÉ evidente que, ao avaliar o índice de correlação entre o tempo de resolução de prova e a quantidade de horas de estudo, não ha quase nenhuma relação entre essas variáveis, sendo assim, as horas de estudo não influenciam no tempo de resolução de prova dos alunos")

                 tempo_resolucao  horas_estudo
tempo_resolucao         1.000000      0.059977
horas_estudo            0.059977      1.000000

ANÁLISE
É evidente que, ao avaliar o índice de correlação entre o tempo de resolução de prova e a quantidade de horas de estudo, não ha quase nenhuma relação entre essas variáveis, sendo assim, as horas de estudo não influenciam no tempo de resolução de prova dos alunos

## Exercício 16
Descreva e analise algo relevante nos dados.

In [209]:
faltas_acessos = df[['faltas','acessos_plataforma']].corr()
print(faltas_acessos)
print("\nANÁLISE\nAnalisando o índice de correlação entre as faltas dos alunos e a quantidade de acessos à plataforma, concluimos que não há nenhuma relação entre esses dois fatores, e as faltas não afetam em nada praticamente nos acessos à plataforma, sendo assim, quem falta mais não usa menos ou mais a plataforma")

                      faltas  acessos_plataforma
faltas              1.000000           -0.007704
acessos_plataforma -0.007704            1.000000

ANÁLISE
Analisando o índice de correlação entre as faltas dos alunos e a quantidade de acessos à plataforma, concluimos que não há nenhuma relação entre esses dois fatores, e as faltas não afetam em nada praticamente nos acessos à plataforma, sendo assim, quem falta mais não usa menos ou mais a plataforma

## Exercício 17
Descreva e analise algo relevante nos dados.

In [210]:
faltas_bolsa = df.groupby('bolsa_estagio')['faltas']

print("Média:\n",faltas_bolsa.mean(),"\n\nDesvio padrão:\n",faltas_bolsa.std())
print("\nANÁLISE\nObservando os valores e comparando as faltas dos alunos que possuem bolsa e dos que não possuem, concluimos que os alunos que possuem bolsa de estágio apresentam uma média de faltas ligeiramente maior, mas com um alto desvio padrão, que indica valores bem espalhados")

Média:
 bolsa_estagio
0    4.358974
1    6.146341
Name: faltas, dtype: float64

Desvio padrão:
 bolsa_estagio
0    3.572462
1    3.602506
Name: faltas, dtype: float64

ANÁLISE
Observando os valores e comparando as faltas dos alunos que possuem bolsa e dos que não possuem, concluimos que os alunos que possuem bolsa de estágio apresentam uma média de faltas ligeiramente maior, mas com um alto desvio padrão, que indica valores bem espalhados

## Exercício 18
Descreva e analise algo relevante nos dados.

In [211]:
acessos_turno = df.groupby('turno')['acessos_plataforma']

print("Média:\n",acessos_turno.mean(),"\n\nDesvio padrão:\n", acessos_turno.std())
print("\nANÁLISE\nAo analisar os valores em comparação dos acessos à plataforma em relação aos turnos, podemos notar que os alunos que estudam no turno da noite possuem uma média de acessos a plataforma maior que os alunos do período matutino, contudo, há um alto desvio padrão,que pode indicar algumas discrepâncias")

Média:
 turno
Manhã    51.828571
Noite    66.266667
Name: acessos_plataforma, dtype: float64

Desvio padrão:
 turno
Manhã    33.167565
Noite    33.503324
Name: acessos_plataforma, dtype: float64

ANÁLISE
Ao analisar os valores em comparação dos acessos à plataforma em relação aos turnos, podemos notar que os alunos que estudam no turno da noite possuem uma média de acessos a plataforma maior que os alunos do período matutino, contudo, há um alto desvio padrão,que pode indicar algumas discrepâncias

## Exercício 19
Descreva e analise algo relevante nos dados.

In [212]:
tempo_linguagem = df.groupby('linguagem')['tempo_resolucao']

print("Média:\n",tempo_linguagem.mean(), "\n\nDesvio padrão:\n",tempo_linguagem.std())
print("\nANÁLISE\nObservando os valores e comparando o tempo de resolução de prova dos alunos em relação a cada linguagem, notamos que a média de tempo de resolução de prova para as três linguagens é praticamente o mesmo, não apresentando diferenças significativas, apesar de existir um alto desvio padrão, o que influencia nos valores, tendo uma certa variância")

Média:
 linguagem
C         120.550000
Java      129.645161
Python    132.517241
Name: tempo_resolucao, dtype: float64

Desvio padrão:
 linguagem
C         48.785756
Java      48.933661
Python    48.453675
Name: tempo_resolucao, dtype: float64

ANÁLISE
Observando os valores e comparando o tempo de resolução de prova dos alunos em relação a cada linguagem, notamos que a média de tempo de resolução de prova para as três linguagens é praticamente o mesmo, não apresentando diferenças significativas, apesar de existir um alto desvio padrão, o que influencia nos valores, tendo uma certa variância

## Exercício 20
Descreva e analise algo relevante nos dados.

In [213]:
df['eficiencia'] = df['nota'] / df['horas_estudo']

eficiencia_turno = df.groupby('turno')['eficiencia']

print("Média de eficiência por turno:\n",eficiencia_turno.mean(), "\n\nDesvio:\n",eficiencia_turno.std())
print("\nANÁLISE\nAnalisando a eficiência dos alunos em comparação com o período, notamos que os alunos do período matutino apresentam ligeiramente uma maior eficiência que os alunos do período noturno, mas havendo valores espalhados e variados por conta do desvio padrão relativamente alto")

Média de eficiência por turno:
 turno
Manhã    8.199836
Noite    7.338731
Name: eficiencia, dtype: float64

Desvio:
 turno
Manhã    3.603496
Noite    2.951961
Name: eficiencia, dtype: float64

ANÁLISE
Analisando a eficiência dos alunos em comparação com o período, notamos que os alunos do período matutino apresentam ligeiramente uma maior eficiência que os alunos do período noturno, mas havendo valores espalhados e variados por conta do desvio padrão relativamente alto