# 📊 Estudo de Caso: Desempenho de Alunos

Você foi contratado como cientista de dados para analisar o desempenho de uma turma.
Seu objetivo é gerar insights para melhorar o ensino.

Utilizando o material e as métricas apresentadas na aula de hoje, apresente seus _insigths_ para o _dataset_ apresentado:

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('dataset_estudo_estatistica.csv')
df.head()

,horas_estudo,acessos_plataforma,faltas,tempo_resolucao,bolsa_estagio,turno,linguagem,nota
0,7,39,10,167,1,Manhã,Java,75.596400
1,4,39,9,183,1,Manhã,Java,0.000000
2,8,37,6,166,0,Manhã,C,66.178579
3,5,9,11,109,0,Noite,Python,35.059806
4,7,110,8,166,1,Noite,C,57.371902

## Exercício 1
Descreva e analise algo relevante nos dados.

In [5]:
#Vamos primeiro tirar a media basica das horas de estudo
print("Conferindo media de horas de estudo")
df['horas_estudo'].mean()

np.float64(5.3625)

## Exercício 2
Descreva e analise algo relevante nos dados.

In [6]:
#Vamos olhar agora o mean para ver se difere muito da media basica
print("Conferindo mediana de horas de estudo")
df['horas_estudo'].median()

np.float64(5.0)

## Exercício 3
Descreva e analise algo relevante nos dados.

In [8]:
#Vimos que nao difere tanto, vamos tentar criar uma coluna para acesso por hora
print("Criando uma coluna para acessos por hora")
df['acessos_hora'] = df['acessos_plataforma']/ df['horas_estudo']
df.head()

,horas_estudo,acessos_plataforma,faltas,tempo_resolucao,bolsa_estagio,turno,linguagem,nota,acessos_hora
0,7,39,10,167,1,Manhã,Java,75.596400,5.571429
1,4,39,9,183,1,Manhã,Java,0.000000,9.750000
2,8,37,6,166,0,Manhã,C,66.178579,4.625000
3,5,9,11,109,0,Noite,Python,35.059806,1.800000
4,7,110,8,166,1,Noite,C,57.371902,15.714286

## Exercício 4
Descreva e analise algo relevante nos dados.

In [9]:
#vou conferir agora median e mean de acesos por hora
print(Media de acessos por hora)
df['acessos_hora'].mean()

np.float64(17.28123511904762)

## Exercício 5
Descreva e analise algo relevante nos dados.

In [10]:
print("Mediana de acessos por hora")
df['acessos_hora'].median()

np.float64(10.422222222222222)

## Exercício 6
Descreva e analise algo relevante nos dados.

In [13]:
print("Variancia de acessos por hora)
df['acessos_hora'].var()

np.float64(361.21433443520255)

## Exercício 7
Descreva e analise algo relevante nos dados.

In [15]:
#vamos ver em que turno eh mais utilizado
print(Conferindo qual turno eh mais utilizado)
df['turno'].mode()

0    Noite
Name: turno, dtype: object

## Exercício 8
Descreva e analise algo relevante nos dados.

In [16]:
#vendo a linguagem mais utilizada
print("Vendo a linguagem mais utilizada")
df['linguagem'].mode()

0    Java
Name: linguagem, dtype: object

## Exercício 9
Descreva e analise algo relevante nos dados.

In [17]:
#vamos dar uma olhada agora nas faltas
print("Media de faltas")
df['faltas'].mean()

np.float64(5.0)

## Exercício 10
Descreva e analise algo relevante nos dados.

In [18]:
print("Mediana de faltas)
df['faltas'].median()

np.float64(5.0)

## Exercício 11
Descreva e analise algo relevante nos dados.

In [19]:

print("Conferindo correlacao entre o tempo de resolucao e notas")
df['horas_estudo'].corr(df['nota'])
print("Correlacao muito positiva")

np.float64(0.9180856640311844)

## Exercício 12
Descreva e analise algo relevante nos dados.

In [22]:
#voltando no acessos hora, que median e media mudou muito, vamos conferir quartis e outliers
print("Outliers:")
q1 = df['acessos_hora'].quantile(0.25)
q3 = df['acessos_hora'].quantile(0.75)
iqr = q3 - q1
l_superior = q3 + 1.5 * iqr
l_inferior = q1 - 1.5 * iqr
outliers1 = df[df['acessos_hora'] > l_superior]
outliers2= df[df['acessos_hora'] < l_inferior]
print(outliers1)
print(outliers2)

    horas_estudo  acessos_plataforma  faltas  tempo_resolucao  bolsa_estagio  \
20             1                  48       0              118              0
23             1                  95      11              109              1
35             2                 107       6              166              1
46             1                 107       1              132              0
51             2                  98       0              131              1
64             2                 119      10               52              1
69             1                  49       3              147              0

    turno linguagem       nota  acessos_hora
20  Manhã    Python   9.749181          48.0
23  Noite      Java   0.000000          95.0
35  Noite         C   6.438283          53.5
46  Noite    Python   7.853039         107.0
51  Noite      Java  18.235311          49.0
64  Manhã      Java   0.000000          59.5
69  Noite      Java   2.080738          49.0
Empty DataFrame
Columns: [horas_estudo, acessos_plataforma, faltas, tempo_resolucao, bolsa_estagio, turno, linguagem, nota, acessos_hora]
Index: []

## Exercício 13
Descreva e analise algo relevante nos dados.

In [24]:
#Quantos alunos sera que recebem bolsa de estagio?
df['bolsa_estagio'].sum()
print("41 alunos possuem bolsa de estagio")

41 alunos possuem bolsa de estagio

## Exercício 14
Descreva e analise algo relevante nos dados.

In [30]:
df.count()
sem_estagio = 80 - 41
print("Alunos sem estagio:")
print(sem_estagio)

Alunos sem estagio:
39

## Exercício 15
Descreva e analise algo relevante nos dados.

In [46]:
#temos 7 outliers
print("Numero de outliers")
len(outliers)

Numero de outliers

7

## Exercício 16
Descreva e analise algo relevante nos dados.

In [45]:
len(df)
print("Porcentagem de outliers em acessos_hora")
print(7/80 * 100)

Porcentagem de outliers em acessos_hora
8.75

## Exercício 17
Descreva e analise algo relevante nos dados.

In [47]:
#Vamos ver se ha uma variancia muito grande em numero de faltas
print("Variancia das faltas")
df['faltas'].var()

np.float64(13.518354430379748)

## Exercício 18
Descreva e analise algo relevante nos dados.

In [49]:
#parece que o tempo varia bastante
print("Vamosv ver o desvio do tempo de resolucao")
print(df['tempo_resolucao'].std())

np.float64(48.334984512753294)

## Exercício 19
Descreva e analise algo relevante nos dados.

In [51]:
#vamos ver se consiste com o median e com o mean
print("Media")
print(df['tempo_resolucao'].mean())
print("Mediana")
print(df['tempo_resolucao'].median())

Media
128.4125
Mediana
138.5

## Exercício 20
Descreva e analise algo relevante nos dados.

In [56]:
print("Numero total de acessos na plataforma:")
print(df['acessos_plataforma'].sum())
print("Numero total de horas de estudos")
print(df['horas_estudo'].sum())
print("Tempo medio por acesso")
print("Tempo por acesso em horas:")
print(429/4796)

Numero total de acessos na plataforma:
4796
Numero total de horas de estudos
429
Tempo medio por acesso
Tempo por acesso em horas:
0.08944954128440367